import type { OfficeState } from "../../types/office";
import { AgentGrid } from "../office/AgentGrid";
import { ConversationPanel } from "../conversation/ConversationPanel";
import { MetricCard } from "./MetricCard";
import { TaskBoard } from "../tasks/TaskBoard";
import { NotificationCenter } from "../notifications/NotificationCenter";
import type { InAppNotification } from "../../store/office-store";
import { AgentOverlay } from "../overlay/AgentOverlay";
import { OverlaySettings } from "../settings/OverlaySettings";
import { V2ControlPanel } from "../v2/V2ControlPanel";
import type { V2State } from "../../types/office";
import { WorkflowStrip } from "../workflow/WorkflowStrip";
import { PixelOfficeMap } from "../office/PixelOfficeMap";
import { LiveActivity } from "../activity/LiveActivity";

type Props = { data: OfficeState; v2: V2State | null; draft: string; notices: InAppNotification[]; overlayEnabled: boolean; onDraftChange: (value: string) => void; onSend: () => void; onRunTask: (id: string) => void; onCreateMeeting: () => void; onEnableNotifications: () => void; onDismissNotification: (id: string) => void; onOverlayChange: (enabled: boolean) => void; onRequestTool: (id: string, input?: Record<string, unknown>) => void; onApproveTool: (id: string) => void };
export function Dashboard({ data, v2, draft, notices, overlayEnabled, onDraftChange, onSend, onRunTask, onCreateMeeting, onEnableNotifications, onDismissNotification, onOverlayChange, onRequestTool, onApproveTool }: Props) { const active = data.projects[0]; return <main className="shell"><header><div className="brand-lockup"><div className="brand-mark">✦</div><div><span className="eyebrow">AI OFFICE / COMMAND CENTER</span><h1>{active?.name ?? "AI Office"}</h1><p className="muted">오늘도 AI 직원들이 대표님의 프로젝트를 운영하고 있어요.</p></div></div><div className="header-actions"><button className="secondary-button" onClick={onEnableNotifications}>🔔 알림</button><button className="primary-button" onClick={onCreateMeeting}>+ 회의 시작</button><span className="status-pill"><i /> {active?.status ?? "PLANNING"}</span></div></header><WorkflowStrip /><section className="command-bar"><div><span className="section-kicker">CEO DESK</span><strong>대표 지시창</strong><span className="muted">업무를 입력하면 담당 에이전트가 배정됩니다.</span></div><form onSubmit={(event) => { event.preventDefault(); onSend(); }}><input value={draft} onChange={(event) => onDraftChange(event.target.value)} placeholder="예: 오늘 콘텐츠 성과를 분석하고 다음 주 기획안을 준비해줘" /><button type="submit">지시 보내기 <span>↗</span></button></form></section>{v2 && <V2ControlPanel state={v2} onRequest={onRequestTool} onApprove={onApproveTool} />}<section className="metrics"><MetricCard label="진행 중 Task" value={String(data.tasks.filter((t) => t.status === "IN_PROGRESS").length)} /><MetricCard label="온라인 Agent" value={`${data.agents.filter((a) => a.status !== "IDLE").length}/${data.agents.length}`} /><MetricCard label="오늘의 회의" value={String(data.meetings.length)} /><MetricCard label="누적 활동" value={String(data.events.length)} /></section><div className="dashboard-grid"><section className="panel office office-map-panel"><div className="panel-title"><div><span className="section-kicker">OFFICE MAP</span><h2>AI 직원 사무실</h2></div><span className="muted">{data.agents.length}명의 직원이 근무 중</span></div><PixelOfficeMap agents={data.agents} /></section><div className="side-column"><LiveActivity events={data.events} /><TaskBoard tasks={data.tasks} onRun={onRunTask} /></div><section className="panel roster-panel"><div className="panel-title"><div><span className="section-kicker">STAFF ROSTER</span><h2>직원 현황</h2></div><span className="muted">{data.agents.length} agents</span></div><AgentGrid agents={data.agents} /></section><ConversationPanel messages={data.messages} draft={draft} onDraftChange={onDraftChange} onSend={onSend} /></div><section className="panel settings-panel"><div className="panel-title"><h2>Settings</h2><span className="muted">오버레이 표시 설정</span></div><OverlaySettings enabled={overlayEnabled} onChange={onOverlayChange} /></section>{overlayEnabled && <AgentOverlay agents={data.agents} />}<NotificationCenter notices={notices} onDismiss={onDismissNotification} /></main>; }
