export const config = {
  port: Number(process.env.API_PORT ?? 4000),
  webOrigin: process.env.WEB_ORIGIN ?? "http://localhost:3000",
  githubToken: process.env.GITHUB_TOKEN ?? "",
  githubApiUrl: process.env.GITHUB_API_URL ?? "https://api.github.com",
  githubRepository: process.env.GITHUB_REPOSITORY ?? "081114ysm/AIOFFICE",
  databaseUrl: process.env.DATABASE_URL ?? "",
  openaiApiKey: process.env.OPENAI_API_KEY ?? "",
  openaiModel: process.env.AI_MODEL || "gpt-5",
  openaiPerMinuteLimit: Number(process.env.AI_PER_MINUTE_LIMIT ?? 20),
  openaiDailyLimit: Number(process.env.AI_DAILY_LIMIT ?? 100),
  githubClientId: process.env.GITHUB_CLIENT_ID ?? "",
  githubClientSecret: process.env.GITHUB_CLIENT_SECRET ?? "",
  authCallbackUrl: process.env.AUTH_CALLBACK_URL ?? "http://localhost:4000/api/auth/callback/github",
  authSessionDays: Number(process.env.AUTH_SESSION_DAYS ?? 7),
};
