import { createId, now } from "../../common/id.mjs";
import { pool } from "../../infrastructure/database/postgres.mjs";
import { publish } from "../../infrastructure/events/event-bus.mjs";
import { executeTool } from "./tool-adapters.mjs";

const tools = [
  { id: "tool-github-read", name: "GitHub Read", type: "GITHUB", description: "Repository와 파일을 읽습니다.", risk: "LOW", enabled: true },
  { id: "tool-terminal", name: "Terminal", type: "TERMINAL", description: "허용된 read-only 명령만 workspace에서 실행합니다.", risk: "HIGH", enabled: true },
  { id: "tool-file-system", name: "File System", type: "FILE_SYSTEM", description: "승인된 workspace 파일을 읽고 수정합니다.", risk: "HIGH", enabled: true },
  { id: "tool-file-read", name: "File Read", type: "FILE_SYSTEM_READ", description: "workspace 내부 파일을 읽습니다.", risk: "LOW", enabled: true },
  { id: "tool-github-commit", name: "GitHub Commit", type: "GITHUB_WRITE", description: "승인 후 지정 파일을 GitHub branch에 커밋합니다.", risk: "HIGH", enabled: true },
  { id: "tool-github-pr", name: "GitHub Pull Request", type: "GITHUB_WRITE", description: "승인 후 GitHub Pull Request를 생성합니다.", risk: "HIGH", enabled: true },
  { id: "tool-codex-inspect", name: "Codex 분석", type: "CODEX_READ_ONLY", description: "승인 후 workspace를 읽고 구현 계획을 반환합니다.", risk: "MEDIUM", enabled: true },
];
const toolMap = { "tool-github-read": "github.read", "tool-terminal": "terminal.exec", "tool-file-system": "filesystem.write", "tool-file-read": "filesystem.read", "tool-github-commit": "github.commit", "tool-github-pr": "github.pr", "tool-codex-inspect": "codex.inspect" };
const defaultAgentId = "11111111-1111-4111-8111-111111111111";

export async function listV2() { const [runs, memberships] = await Promise.all([pool.query("select id, tool_id, project_id, requested_by, status, input, output, created_at, completed_at from tool_runs order by created_at desc limit 50"), pool.query("select project_id, agent_id, role from project_agents order by role")]); return { organization: { id: "workspace", name: "AI Office Workspace", owner: "CEO" }, tools, memberships: memberships.rows.map((row) => ({ id: `${row.project_id}:${row.agent_id}`, organizationId: "workspace", agentId: row.agent_id, role: row.role })), toolRuns: runs.rows.map((row) => ({ id: row.id, toolId: row.tool_id, projectId: row.project_id, requestedBy: row.requested_by, status: row.status, input: row.input, output: row.output, createdAt: row.created_at, completedAt: row.completed_at })), approvals: runs.rows.filter((row) => row.status === "PENDING_APPROVAL").map((row) => ({ id: `approval:${row.id}`, targetId: row.id, status: "PENDING" })) }; }
export async function hireAgent(input) { if (!input.projectId || !input.agentId || !input.role) throw Object.assign(new Error("projectId, agentId, role이 필요합니다."), { statusCode: 400 }); await pool.query("insert into project_agents (project_id, agent_id, role) values ($1, $2, $3) on conflict (project_id, agent_id) do update set role = excluded.role", [input.projectId, input.agentId, input.role]); return { id: `${input.projectId}:${input.agentId}`, organizationId: "workspace", agentId: input.agentId, role: input.role, hiredAt: now() }; }
export async function requestToolRun(input) { const tool = tools.find((item) => item.id === input.toolId); if (!tool || !tool.enabled) throw Object.assign(new Error("사용할 수 없는 Tool입니다."), { statusCode: 404 }); const run = { id: createId(), toolId: tool.id, projectId: input.projectId, requestedBy: input.agentId || defaultAgentId, input: input.input || {} }; const result = await pool.query("insert into tool_runs (id, tool_id, project_id, requested_by, status, input) values ($1, $2, $3, $4, 'PENDING_APPROVAL', $5) returning id, tool_id, project_id, requested_by, status, input, created_at", [run.id, run.toolId, run.projectId, run.requestedBy, JSON.stringify(run.input)]); await pool.query("insert into approvals (id, target_type, target_id, status) values ($1, 'TOOL_RUN', $2, 'PENDING')", [createId(), run.id]); publish("TOOL_RUN_REQUESTED", run.projectId, { runId: run.id, toolId: run.toolId }); return result.rows[0]; }
export async function approveToolRun(runId) { const run = (await pool.query("select id, tool_id, project_id, status, input from tool_runs where id = $1", [runId])).rows[0]; if (!run) throw Object.assign(new Error("Tool run not found"), { statusCode: 404 }); if (run.status !== "PENDING_APPROVAL") throw Object.assign(new Error("대기 중인 Tool Run만 승인할 수 있습니다."), { statusCode: 409 }); await pool.query("update approvals set status = 'APPROVED', decided_at = now() where target_type = 'TOOL_RUN' and target_id = $1 and status = 'PENDING'", [runId]); await pool.query("update tool_runs set status = 'RUNNING' where id = $1", [runId]); publish("TOOL_RUN_APPROVED", run.project_id, { runId }); try { const output = await executeTool(toolMap[run.tool_id], run.input); const saved = (await pool.query("update tool_runs set status = 'COMPLETED', output = $2, completed_at = now() where id = $1 returning id, tool_id, project_id, status, output, completed_at", [runId, JSON.stringify(output)])).rows[0]; publish("TOOL_RUN_COMPLETED", run.project_id, { runId, output }); return saved; } catch (error) { const message = error instanceof Error ? error.message : "Tool 실행 실패"; const saved = (await pool.query("update tool_runs set status = 'FAILED', output = $2, completed_at = now() where id = $1 returning id, tool_id, project_id, status, output, completed_at", [runId, JSON.stringify({ error: message })])).rows[0]; publish("TOOL_RUN_FAILED", run.project_id, { runId, error: message }); return saved; } }
