import { useState } from "react";
import type { V2State } from "../../types/office";

export function V2ControlPanel({ state, onRequest, onApprove }: { state: V2State; onRequest: (toolId: string, input?: Record<string, unknown>) => void; onApprove: (runId: string) => void }) {
  const [selected, setSelected] = useState(state.tools[0]?.id ?? "");
  const [path, setPath] = useState(""); const [command, setCommand] = useState("pwd"); const [content, setContent] = useState(""); const [prompt, setPrompt] = useState(""); const [branch, setBranch] = useState("main"); const [message, setMessage] = useState("feat: update workspace file"); const [title, setTitle] = useState("AI Office change"); const [body, setBody] = useState("Created after CEO approval by AI Office."); const [head, setHead] = useState(""); const [base, setBase] = useState("main");
  const tool = state.tools.find((item) => item.id === selected);
  function submit() { if (!tool) return; const input: Record<string, unknown> = {}; if (tool.id.includes("file")) { input.path = path; if (tool.id === "tool-file-system") input.content = content; } if (tool.id === "tool-terminal") input.command = command; if (tool.id === "tool-codex-inspect") input.prompt = prompt; if (tool.id === "tool-github-read") { input.path = path; input.ref = branch; } if (tool.id === "tool-github-commit") { input.path = path; input.content = content; input.branch = branch; input.message = message; } if (tool.id === "tool-github-pr") { input.title = title; input.body = body; input.head = head; input.base = base; } onRequest(tool.id, input); }
  return <section className="panel v2-panel"><div className="panel-title"><h2>V2 Tool Center</h2><span className="muted">승인 기반 실제 Adapter</span></div><div className="v2-tools">{state.tools.map((item) => <div className={`v2-tool ${selected === item.id ? "selected" : ""}`} key={item.id}><div><strong>{item.name}</strong><p>{item.description}</p></div><button disabled={!item.enabled} onClick={() => setSelected(item.id)}>{selected === item.id ? "선택됨" : "선택"}</button></div>)}</div><div className="tool-form"><div className="tool-form-heading"><strong>{tool?.name ?? "Tool"} 입력</strong><span className="muted">요청 후 CEO 승인이 필요합니다.</span></div>{tool?.id === "tool-codex-inspect" && <textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder="Codex에게 분석·구현 계획을 시킬 작업을 입력하세요." rows={5} />}{(tool?.id.includes("file") || tool?.id === "tool-github-read" || tool?.id === "tool-github-commit") && <input value={path} onChange={(event) => setPath(event.target.value)} placeholder="workspace 상대 경로 (예: README.md)" />}{tool?.id === "tool-terminal" && <input value={command} onChange={(event) => setCommand(event.target.value)} placeholder="허용 명령 (예: pwd, git status)" />}{(tool?.id === "tool-file-system" || tool?.id === "tool-github-commit") && <textarea value={content} onChange={(event) => setContent(event.target.value)} placeholder="저장할 파일 내용" rows={3} />}{(tool?.id === "tool-github-read" || tool?.id === "tool-github-commit") && <input value={branch} onChange={(event) => setBranch(event.target.value)} placeholder="branch" />}{tool?.id === "tool-github-commit" && <input value={message} onChange={(event) => setMessage(event.target.value)} placeholder="commit message" />}{tool?.id === "tool-github-pr" && <><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="PR 제목" /><textarea value={body} onChange={(event) => setBody(event.target.value)} placeholder="PR 설명" rows={2} /><input value={head} onChange={(event) => setHead(event.target.value)} placeholder="head branch" /><input value={base} onChange={(event) => setBase(event.target.value)} placeholder="base branch" /></>}<button className="tool-submit" onClick={submit}>실행 승인 요청</button></div>{state.toolRuns.filter((run) => run.status === "PENDING_APPROVAL").map((run) => <div className="approval-row" key={run.id}><span>Tool 실행 승인 대기</span><button onClick={() => onApprove(run.id)}>승인</button></div>)}</section>;
}
